config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :attendances
  resources :events
  resources :users do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances
  has_many :events, through: :attendances
  has_one_attached :avatar
  
  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    redirect_to :root
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to '/users/edit'
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main class="container">
  <h1>Editing User</h1>
  
  <%= render 'form', user: @user %>
  
  <%= link_to 'View Profile', @user, class:"btn btn-info" %> |
  <%= link_to 'Home', root_path, class:"btn btn-info" %>
</main>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Description</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.description %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'shared/form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<main class="container">
<p id="notice"><%= notice %></p>

<div class="card" style"width: 18rem;">
  <img class="card-img-top" src="<%= image_tag @user.avatar %> alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"> <%= @user.email %> </h5>
    <p class="card-text"> 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>

<%= link_to 'Edit profil', edit_user_registration_path, class:"btn btn-success" %> |
<%= link_to 'Home', root_path, class:"btn btn-primary" %>

<% Event.all.each do |event| %>
  <% if @user.id == event.admin.id %>
    <div class="card my-3">
      <div class="card-header">
        <h4><%= event.title %></h4>
      </div>
      <div class="card-body">
        <h5 class="card-title">le <%= event.start_date %> à <%= event.location %></h5>
        <p class="card-text"><%= event.description %></p>
        <%= link_to 'Show', event, class:"btn btn-primary" %> 
        <% if user_signed_in? && current_user.id == event.admin.id %>
          <%= link_to 'Edit', edit_event_path(event), class:"btn btn-warning" %> 
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <% end %>
      </div>
      <div class="card-footer">
        Prix : <%= event.price %> € // Durée : <%= event.duration %> min
      </div>
    </div>
  <% end %>
<% end %>

</main>