config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :attendances
  resources :events
  resources :users do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, :duration, :title, :description, :price, :location, presence: true
  validates :title, length: {minimum: 5, maximum: 140}
  validates :description, length: {minimum: 20, maximum: 1000}
  validates :price, numericality: {greater_than: 0, less_than_or_equal_to: 1000}
  validate :multiple_of_five
  validate :cant_be_zero
  validate :cant_be_past
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :users, through: :attendances


  def end_date
    self.start_date + (self.duration * 60)
  end

private 

  def multiple_of_five
    errors.add(:duration, "has to be a multiple of 5") unless duration % 5 == 0 
  end

  def cant_be_zero
    errors.add(:duration, "can't be 0") if duration == 0
  end

  def cant_be_past
    errors.add(:start_date, "can't be past") if start_date < Time.now
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @admin = User.find(@event.admin_id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :admin_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form-event.html.erb
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_date %>
      <%= form.datetime_select :start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :duration %>
      <%= form.range_field :duration, within: 0..120, step: 5, oninput:"updateTextInput(this.value)", id:"inputRange", class:"form-control" %>
      <%= form.number_field :fake, within: 5..120, value: 60, id: "textInput", oninput: "updateRangeInput(this.value)"%>
    </div>


    <div class="form-group">
      <%= form.label :price %>
      <%= form.number_field :price, within: 1..1000, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>

    <%= form.hidden_field :admin_id, value: current_user.id %>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<script>
function updateTextInput(val) {
          document.getElementById('textInput').value=val; 
        }
function updateRangeInput(val) {
  document.getElementById('inputRange').value=val; 
}
</script>

<br><br>

app/views/events/edit.html.erb
<main class="container">
<h1 class="text-center">Editer votre évènement</h1>

<%= render 'form', event: @event %>

<div class="text-center">
<%= link_to "Voir l'évènement", @event, class:"btn btn-info" %> |
<%= link_to '« Retour Accueil', events_path, class:"btn btn-primary" %>
</div>
</main>

app/views/events/index.html.erb
<div class="jumbotron" 
  style="background-image: url(https://www.design.svgbackgrounds.com/wp-content/uploads/2021/05/sun-tornado-orange-spinning-background.jpg);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;">
  <div class="container" style="background-color: rgba(255, 255, 255, 0.6); padding: 25px; border-radius: 20px;">
    <h1 class="display-3">EventBite</h1>
    <p>if you're_pissing_off but you_want_to_create_an_event</p>
    <p><%= link_to 'Create an Event', new_event_path, class:"btn btn-warning btn-lg" %></p>
  </div>
</div>
  
<div class="container">
<h1 class="d-flex justify-content-center">Incoming Events</h1>


<div class="container row justify-content-center">

<% @events.each do |event| %>
  <div class="col-xs-12 col-md-6 col-lg-4">
    <div class="card m-3 card-home" style="width: 18rem;">  
      <img class="card-img-top" src="https://img.freepik.com/vecteurs-libre/stage-spot-lights-rayons-fond-rougeoyant_1017-31524.jpg?size=338&ext=jpg&ga=GA1.2.2136140614.1639267200" alt="Card image cap">
        <div class="card-body">
        <h5 class="card-title"> <%= event.title %> at <%= event.location %></h5>
          <p style="overflow-y:scroll;height:70px" class="card-text"><%= event.description %></p>
          <%= link_to 'Show more', event, class:"btn btn-warning" %> 
        <% if user_signed_in? && current_user.id == event.admin.id %>
         <%= link_to 'Editer', edit_event_path(event), class:"btn btn-success" %> 
         <%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <% end %>
      </div>
        <div class="card-footer">
        Price : <%= event.price %> € | Duration : <%= event.duration %> min
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<main class="container">
  
<h1 class="text-center">Création d'un nouvel évènement</h1>

<%= render 'form-event', event: @event %>

<%= link_to '« Retour Accueil', events_path, class:"btn btn-primary" %>
  
</main>

app/views/events/show.html.erb
<main class="container">
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @event.title %></h1>

<div class="card my-5">
  <div class="card-header">
      <strong>Admin. mail : </strong><%= @admin.email %>
  <!--  <%= link_to 'Voir profil', user_path(@admin.id) %>  sortir également la première ligne de la methode show dans le controleur-->
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Start date : </strong><%= @event.start_date.strftime('%d/%m/%Y à %H:%M') %></li>
    <li class="list-group-item"><strong>End date: </strong><%= @event.end_date.strftime('%d/%m/%Y à %H:%M') %></li>
    <li class="list-group-item"><strong>Price : </strong><%= @event.price %> €</li>
    <li class="list-group-item"><strong>Location : </strong><%= @event.location %></li>
    <li class="list-group-item"><strong>Description : </strong><%= @event.description %></li>
  </ul>
</div>

<% if user_signed_in? && current_user.id == @admin.id %>
  <%= link_to 'Edit', edit_event_path(@event), class:"btn btn-success" %> 
  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>

<%= link_to 'Home', events_path, class:"btn btn-primary" %>
</main>