config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users
  resources :attendances
  resources :events
  resources :users do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :participation_send

  belongs_to :user
  belongs_to :event

  def participation_send
    UserMailer.participation_email(self).deliver_now
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.fetch(:attendance, {})
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>